<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promise</title>
</head>
<body>
      <h4>PROMISES ASYNC AWAIT HANDS-ON</h4>
    <br><hr><br>

    <p><strong>
        1) Write one example explaining how you can write a callback function ?
    </strong></p>
    <pre>
        function cubeFunc(num, operation){
            setTimeout(function(){
                let ans=1;
                ans = num**3;
                operation(num, ans);
            }, 2000)
        }
        
        cubeFunc(9, function(no, ans){
            console.log("The cube of ",no," is = ",ans);
        })
        

        <em>//OUTPUT: The cube of 9 is = 729</em>
    </pre>
    <br><hr><br>

    <p><strong>
        2) Write callback function to print numbers from 1 to 7, in which 1 should be printed after 1 sec , 2 should be printed after 2 sec, 3 should be printed after 3 sec and so on. 
        Explain callback hell. <br>
        Numbers <br>
        1 <br>
        2 <br>
        3 <br>
        4 <br>
        5 <br>
        6 <br>
        7 <br>
    </strong></p>
    <pre>
<strong>Callback Hell is the pattern that forms in our code while using dependents or nested callbacks.</strong>

    let count=0;
    setTimeout(function(){
        console.log(++count);
        setTimeout(function(){
            console.log(++count);
            setTimeout(function(){
                console.log(++count);
                setTimeout(function(){
                    console.log(++count);
                    setTimeout(function(){
                        console.log(++count);
                        setTimeout(function(){
                            console.log(++count);
                            setTimeout(function(){
                                console.log(++count);
                            },7000)
                        },6000)
                    },5000)
                },4000)
            },3000)
        },2000)
    },1000)
    </pre>
    <br><hr><br>

    <p><strong>
        3) Write promise function to print numbers from 1 to 7, in which 1 should be printed after 1 sec , 2 should be printed after 2 sec, 3 should be printed after 3 sec and so on. 
        <br>Numbers<br>
        1 <br>
        2 <br>
        3 <br>
        4 <br>
        5 <br>
        6 <br>
        7 <br>
    </strong></p>
    <pre>
        function printNos(n){
            let P = new Promise(function(resolve){
                setTimeout(function(){
                    resolve(n);
                },n*1000)
            })
            return P;
        }
        
        printNos(1).then(function(n){
            console.log(n);
            return printNos(2);
        }).then(function(n){
            console.log(n);
            return printNos(3);
        }).then(function(n){
            console.log(n);
            return printNos(4);
        }).then(function(n){
            console.log(n);
            return printNos(5);
        }).then(function(n){
            console.log(n);
            return printNos(6);
        }).then(function(n){
            console.log(n);
            return printNos(7);
        }).then(function(n){
            console.log(n);
        })
    </pre>
    <br><hr><br>

    <p><strong>
        4) Create a promise function accepting a argument, if yes is passed to the function then it should go to resolved state and print Promise Resolved, 
        and if nothing is passed then it should go to reject state and catch the error and print Promise Rejected 
    </strong></p>
    <pre>
        function promiseFunc(input){
            let answer = new Promise(function(resolve, reject){
                setTimeout(function(){
                    if(input=="yes")
                    {
                        resolve("Promise Resolved");
                    }
                    else
                    {
                        reject("Promise Rejected");
                    }
                },1000)
            })
            return answer;
        }
        promiseFunc("yes").then(function(res){
            console.log(res);
        }).catch(function(err){
            console.log(err);
        })


        <em>//Promise Resolved</em>
    </pre>
    <br><hr><br>

    <p><strong>
        5) Create example to explain callback function
    </strong></p>
    <pre>
        A callback function is a function passed to another function as an argument. Callbacks promote asynchronous programming

        function findSum(num1, num2, operation1){
            setTimeout(function(){
                let sum = num1 + num2;
                operation1(num1, num2, sum);
            }, 2000)
        }
        
        findSum(26, 23, <strong>function(num1, num2, ans1){</strong>
            console.log("The sum of",num1,"&",num2,":",ans1);
        })

        //The sum of 26 & 23 : 49

        <em>In this example of adding two numbers, there is 1 callback function (shown in bold).</em>
    </pre>
    <br><hr><br>

    <p><strong>
        6) Create example to explain callback hell function
    </strong></p>
    <pre>
        function findSum(num1, num2, operation1){
            setTimeout(function(){
                let sum = num1 + num2;
                operation1(num1, num2, sum);
            }, 2000)
        }
        
        function squareOfSum(num, operation2){
            setTimeout(function(){
                let ans = num * num;
                operation2(num, ans);
            }, 2000)
        }
        
        findSum(26, 23, <strong>function(num1, num2, ans1){</strong>
            console.log("The Sum of",num1,"&",num2,":",ans1);
            squareOfSum(ans1, <strong>function(num, ans2){</strong>
                console.log("The Square of",num,":",ans2);
            })
        })

        //The Sum of 26 & 23 : 49
        //The Square of 49 : 2401

        <em>In this example of adding two numbers and then squaring its sum, there are 2 callback functions (shown in bold).
        And since one callback function is nested within another, a callback hell has formed.</em>
    </pre>
    <br><hr><br>

    <p><strong>
        7) Create example to explain promises function
    </strong></p>
    <pre>
        function findSum(num1,num2){
            let pr = new Promise(function(res,rej){
                setTimeout(function(){
                    let sum = num1 + num2;
                    if(isNaN(sum))
                    {
                        rej("Try Again! Enter a valid number");
                    }
                    else
                    {
                        res(sum);
                    }
                }, 2000)
            })
            return pr;
        }
        
        findSum(26,23).then(function(ans){
            console.log("Sum =", ans);
        }).catch(function(err){
            console.log(err);
        })

        //Sum = 49

        <em>
        Promise Function are the functions that return a promise object. A promise is an object which represents the completion or failure of an asynchronous operation
        along with its result. They come with in-built error handling. Here inside the findSum() function, promise object "pr" has been created.
        Then the function is called and ".then" block is attached to handle the resolved part and ".catch" handles the reject part.</em>
    </pre>
    <br><hr><br>

    <p><strong>
        8) Create example to explain async await function
    </strong></p>
    <pre>
        function findSum(num1,num2){
            let pr = new Promise(function(res,rej){
                setTimeout(function(){
                    let sum = num1 + num2;
                    if(isNaN(sum))
                    {
                        rej("Try Again! Enter a valid number");
                    }
                    else
                    {
                        res(sum);
                    }
                }, 2000)
            })
            return pr;
        }

        async function answer(){
            try
            {
                let finalAns = await findSum(37,26);
                console.log("The Sum = ",finalAns);
            }
            catch
            {
                console.log("Please enter a valid number!");
            }
        }
        answer();

        //The Sum =  63

        <em>
        An async function "answer()" is created, inside which there are two blocks: try block that handles the resolved result, and catch block to handle the rejected result.
        Async Functions always return a promise. Inside the try block, we use the "await" keyword. The "await" keyword can only be used inside functions that are declared with "async".
        "await" pauses the execution of the function, waiting for a promise to be reolved.
        </em>
    </pre>
    <br><hr><br>

    <p><strong>
        9) Create example to explain promise.all function
    </strong></p>
    <pre>
        function add(x1,x2){
            let p1 = new Promise((res,rej)=>{
                setTimeout(()=>{
                    let sum = x1 + x2;
                    if(isNaN(sum))
                    {
                        rej("Enter a valid number");
                    }
                    else
                    {
                        res(sum);
                    }
                },2000)
            })
            return p1;
        }
        
        function mul(y1,y2){
            let p2 = new Promise((res,rej)=>{
                setTimeout(()=>{
                    let product = y1 * y2;
                    if(isNaN(product))
                    {
                        rej("Enter a valid number");
                    }
                    else
                    {
                        res(product);
                    }
                },2000)
            })
            return p2;
        }
        
        function subtract(z1,z2){
            let p3 = new Promise((res,rej)=>{
                setTimeout(()=>{
                    let diff=0;
                    if(z1>z2)
                    {
                        diff = z1 - z2;
                    }
                    else
                    {
                        diff = z2 - z1;
                    }
                    
                    if(isNaN(diff))
                    {
                        rej("Enter a valid number");
                    }
                    else
                    {
                        res(diff);
                    }
                },2000)
            })
            return p3;
        }
        
        Promise.all([add(3,5),mul(13,24),subtract(12,56)]).then((result)=>{
            console.log(result);
            console.log(result[0]);
            console.log(result[1]);
            console.log(result[2]);
        }).catch((error)=>{
            console.log(error);
        })

        //[ 8, 312, 44 ]
        //8
        //312
        //44
    </pre>
    <br><hr><br>
</body>
</html>